spring.config.import=optional:file:.env[.properties],optional:file:.local.env[.properties]

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${EXECUTE_SQL_DDL}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.sql.init.mode=${EXECUTE_SQL_INSERT}
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.defer-datasource-initialization=true
jwt.secret=${JWT_SECRET}
